# The Docker image to run your workspace in. Defaults to gitpod/workspace-full

image: gitpod/workspace-full

# Command to start on workspace startup (optional)
tasks:
  - init: curl -fsSL https://deno.land/x/install/install.sh | sh && export DENO_INSTALL="/home/gitpod/.deno" && export PATH="$DENO_INSTALL/bin:$PATH"
    command: deno run -A --unstable -c tsconfig.json server.ts

ports:
  - port: 8000
    onOpen: open-preview
