name: ci_std

on: 
  push:
    branch: master

jobs:
  build:
    name: lint_and_test ${{ matrix.config.os }}
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'denoland:')
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        config:
          - os: ubuntu-18.04

      fail-fast:
        ${{ github.event_name == 'pull_request' || (github.ref !=
        'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')) }}

    steps:
      - name: Configure git
        run: git config --global core.symlinks true

      - name: Clone repository
        uses: actions/checkout@v1
        with:
          # Use depth > 1, because sometimes we need to rebuild master and if
          # other commits have landed it will become impossible to rebuild if
          # the checkout is too shallow.
          fetch-depth: 5
          submodules: true

      - name: Install latest deno release
        run: |
          denoTestingVersion=$(grep DENO_VERSION < std/version.ts | sed -e 's/.*"\(.*\)".*/\1/')
          echo "Testing with deno::$denoTestingVersion"
          curl -L https://deno.land/x/install/install.sh | sh -s $denoTestingVersion

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "2.7"
          architecture: x64

      - name: Remove unused versions of Python
        if: startsWith(matrix.config.os, 'windows')
        run: |-
          $env:PATH -split ";" |
            Where-Object { Test-Path "$_\python.exe" } |
            Select-Object -Skip 1 |
            ForEach-Object { Move-Item "$_" "$_.disabled" }

      - name: Log versions
        run: |
          python --version
          /home/runner/.deno/bin/deno --version

      - name: lint.py
        run: python ./tools/lint.py --js

      - name: test_format.py
        run: python ./tools/test_format.py

      - name: Test deno server
        run: |
          /home/runner/.deno/bin/deno run --unstable -A server.ts